// Database types for HOA Administration Platform
// TODO: Can be auto-generated by: supabase gen types typescript --local

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      // Core tables from platform-dashboard
      communities: {
        Row: {
          id: string
          name: string
          location: string
          contact_email: string
          contact_phone: string
          subscription_plan_id: string
          regional_settings: Json
          logo_url: string | null
          status: 'active' | 'suspended' | 'deleted'
          deleted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['communities']['Row'],
          'id' | 'created_at' | 'updated_at'
        >
        Update: Partial<Database['public']['Tables']['communities']['Insert']>
      }
      residences: {
        Row: {
          id: string
          tenant_id: string
          unit_number: string
          type: 'single_family' | 'townhouse' | 'condo' | 'apartment'
          max_occupancy: number
          lot_area: number | null
          floor_area: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['residences']['Row'],
          'id' | 'created_at' | 'updated_at'
        >
        Update: Partial<Database['public']['Tables']['residences']['Insert']>
      }
      gates: {
        Row: {
          id: string
          tenant_id: string
          name: string
          type: 'vehicle' | 'pedestrian' | 'service' | 'delivery'
          operating_hours: Json
          latitude: number
          longitude: number
          hardware_settings: Json
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['gates']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['gates']['Insert']>
      }
      admin_users: {
        Row: {
          id: string
          tenant_id: string | null
          role: 'superadmin' | 'admin_head' | 'admin_officer'
          status: 'active' | 'deactivated'
          first_name: string | null
          last_name: string | null
          phone: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['admin_users']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['admin_users']['Insert']>
      }

      // HOA Admin tables
      households: {
        Row: {
          id: string
          tenant_id: string
          residence_id: string
          household_head_id: string | null
          move_in_date: string
          move_out_date: string | null
          status: 'active' | 'inactive' | 'moved_out'
          contact_email: string | null
          contact_phone: string | null
          notes: string | null
          deleted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['households']['Row'],
          'id' | 'created_at' | 'updated_at'
        >
        Update: Partial<Database['public']['Tables']['households']['Insert']>
      }
      household_members: {
        Row: {
          id: string
          tenant_id: string
          household_id: string
          user_id: string | null
          first_name: string
          last_name: string
          relationship_to_head:
            | 'self'
            | 'spouse'
            | 'child'
            | 'parent'
            | 'sibling'
            | 'grandparent'
            | 'grandchild'
            | 'other'
          date_of_birth: string | null
          contact_email: string | null
          contact_phone: string | null
          member_type: 'resident' | 'beneficial_user'
          photo_url: string | null
          status: 'active' | 'inactive'
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['household_members']['Row'],
          'id' | 'created_at' | 'updated_at'
        >
        Update: Partial<Database['public']['Tables']['household_members']['Insert']>
      }
      vehicle_stickers: {
        Row: {
          id: string
          tenant_id: string
          household_id: string
          member_id: string | null
          vehicle_plate: string
          vehicle_make: string | null
          vehicle_model: string | null
          vehicle_color: string | null
          rfid_code: string | null
          or_cr_document_url: string | null
          status:
            | 'requested'
            | 'approved'
            | 'active'
            | 'expiring'
            | 'expired'
            | 'rejected'
            | 'revoked'
          expiry_date: string | null
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          revocation_reason: string | null
          revoked_by: string | null
          revoked_at: string | null
          deleted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['vehicle_stickers']['Row'],
          'id' | 'created_at' | 'updated_at'
        >
        Update: Partial<Database['public']['Tables']['vehicle_stickers']['Insert']>
      }
      construction_permits: {
        Row: {
          id: string
          tenant_id: string
          household_id: string
          project_description: string
          project_start_date: string
          project_end_date: string
          contractor_name: string
          contractor_contact: string | null
          contractor_license: string | null
          estimated_worker_count: number | null
          road_fee_amount: number | null
          road_fee_paid: boolean
          road_fee_paid_at: string | null
          status: 'pending' | 'approved' | 'rejected' | 'in_progress' | 'completed'
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          notes: string | null
          deleted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['construction_permits']['Row'],
          'id' | 'created_at' | 'updated_at'
        >
        Update: Partial<Database['public']['Tables']['construction_permits']['Insert']>
      }
      association_fees: {
        Row: {
          id: string
          tenant_id: string
          household_id: string
          fee_type: 'monthly' | 'quarterly' | 'annual' | 'special_assessment'
          amount: number
          due_date: string
          payment_status: 'unpaid' | 'paid' | 'overdue' | 'waived' | 'partial'
          paid_amount: number
          payment_date: string | null
          payment_method: 'cash' | 'check' | 'bank_transfer' | 'credit_card' | 'online' | null
          receipt_url: string | null
          waived_by: string | null
          waived_at: string | null
          waiver_reason: string | null
          recorded_by: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['association_fees']['Row'],
          'id' | 'created_at' | 'updated_at'
        >
        Update: Partial<Database['public']['Tables']['association_fees']['Insert']>
      }
      announcements: {
        Row: {
          id: string
          tenant_id: string
          created_by: string
          announcement_type: 'general' | 'urgent' | 'event' | 'maintenance' | 'fee_reminder' | 'election'
          title: string
          content: string
          target_audience: 'all' | 'households' | 'security' | 'admins'
          status: 'draft' | 'scheduled' | 'published' | 'expired' | 'archived'
          publication_date: string | null
          expiry_date: string | null
          view_count: number
          click_count: number
          attachment_urls: Json
          published_at: string | null
          archived_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['announcements']['Row'],
          'id' | 'created_at' | 'updated_at'
        >
        Update: Partial<Database['public']['Tables']['announcements']['Insert']>
      }
      gate_entries: {
        Row: {
          id: string
          tenant_id: string
          gate_id: string
          entry_timestamp: string
          entry_type: 'vehicle' | 'pedestrian' | 'delivery' | 'visitor'
          vehicle_plate: string | null
          sticker_id: string | null
          household_id: string | null
          security_officer_id: string | null
          notes: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['gate_entries']['Row'], 'id' | 'created_at'>
        Update: never // Read-only for admins
      }
      incident_reports: {
        Row: {
          id: string
          tenant_id: string
          reported_by: string
          incident_timestamp: string
          incident_type:
            | 'suspicious_activity'
            | 'unauthorized_entry'
            | 'disturbance'
            | 'emergency'
            | 'property_damage'
            | 'other'
          location: string
          gate_id: string | null
          household_id: string | null
          description: string
          resolution_status: 'open' | 'investigating' | 'resolved' | 'closed'
          resolution_notes: string | null
          resolved_by: string | null
          resolved_at: string | null
          attachment_urls: Json
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['incident_reports']['Row'],
          'id' | 'created_at' | 'updated_at'
        >
        Update: Partial<Database['public']['Tables']['incident_reports']['Insert']>
      }
    }
    Views: {
      household_stats: {
        Row: {
          tenant_id: string
          active_households: number
          inactive_households: number
          moved_out_households: number
          total_residences: number
          vacant_residences: number
          occupancy_rate: number
        }
      }
      sticker_dashboard: {
        Row: {
          tenant_id: string
          requested_count: number
          approved_count: number
          active_count: number
          expiring_count: number
          expired_count: number
          rejected_count: number
          revoked_count: number
          approval_rate: number
        }
      }
      fee_summary: {
        Row: {
          tenant_id: string
          total_fees: number
          paid_count: number
          unpaid_count: number
          overdue_count: number
          partial_count: number
          total_billed: number
          total_collected: number
          outstanding_balance: number
          collection_rate: number
        }
      }
    }
    Functions: {
      approve_sticker_bulk: {
        Args: {
          p_sticker_ids: string[]
          p_expiry_date?: string
        }
        Returns: {
          success: boolean
          approved_count: number
        }
      }
      record_fee_payment: {
        Args: {
          p_fee_id: string
          p_amount: number
          p_payment_date: string
          p_payment_method: string
        }
        Returns: {
          success: boolean
          new_status: string
          total_paid: number
        }
      }
      revoke_sticker: {
        Args: {
          p_sticker_id: string
          p_reason: string
        }
        Returns: {
          success: boolean
        }
      }
    }
  }
}
